version: "3"
services:
  order-jdbc:
    image: simple-order-service:dev
    ports:
      - "8083:8083"
    networks:
      - simple-order-mysql
    environment:
      - MYSQL_USER:"web_user"
      - MYSQL_PASSWORD:"Password"
      - MYSQL_DATABASE:"simple_order_service"
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
    networks:
      - simple-order-mysql
    environment:
      - MYSQL_USER:"web_user"
      - MYSQL_PASSWORD:"Password"
      - MYSQL_DATABASE:"simple_order_service" 
    volumes:
         - db_data:/var/lib/mysql

volumes:
    db_data: {}
    
networks:
  simple-order-mysql: 
  
