
version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=simple-order-service
      - MYSQL_USER=web_user
      - MYSQL_PASSWORD=Password
    ports:
      - 3306:3306

  app:
    image: mlnarayana95/simple-order-service:dev
    ports:
       - 8083:8083
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/simple-order-service?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
       - docker-mysql